apps/cart/urls.py
from django.conf.urls import url, include
from cart.views import CartView, CartAddView, CartUpdateView, CartDeleteView

urlpatterns = [
    url(r'^cart$', CartView.as_view(), name='cart'),
    url(r'^add$', CartAddView.as_view(), name='add'),
    url(r'^update$', CartUpdateView.as_view(), name='update'),
    url(r'^delete$', CartDeleteView.as_view(), name='delete')
]

apps/goods/urls.py
from django.conf.urls import url, include
from goods.views import GoodsIndex, DailyDetailView, OrderDetailView, OrderGoodsList, DailyGoodsList

urlpatterns = [
    url(r'daily-detail/(?P<gid>\d+)/(?P<page>\d+)', DailyDetailView.as_view(), name='daily-detail'),
    url(r'order-detail/(?P<gid>\d+)/(?P<page>\d+)', OrderDetailView.as_view(), name='order-detail'),
    url(r'list/(?P<type_id>\d+)/(?P<page>\d+)$', DailyGoodsList.as_view(), name='daily-list'),
    url(r'list/(?P<type_id>\d+)/(?P<num>\d+)/(?P<page>\d+)', OrderGoodsList.as_view(), name='order-list'),
    url(r'^', GoodsIndex.as_view(), name='goodsindex')
]

apps/user/urls.py
from django.conf.urls import url, include
from user.views import RegisterView, LoginView, CenterView, SiteView, OrderView, LogOutView, ChangeView

urlpatterns = [
    url(r'^register$', RegisterView.as_view(), name='register'),
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^logout$', LogOutView.as_view(), name='logout'),
    url(r'^user-center-info$', CenterView.as_view(), name='user-center-info'),
    url(r'^user-info-site$', SiteView.as_view(), name='user-info-site'),
    url(r'^user-center-order/(?P<page>\d+)', OrderView.as_view(), name='user-center-order'),
    url(r'^change$', ChangeView.as_view(), name='change'),
]

quickbutton/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url(r'^search', include('haystack.urls')),  # 全文检索框架
    # url(r'^static_search', include('haystack.urls')),
    url(r'^user/', include(('user.urls', 'user'), namespace='user')),

    url(r'^order/', include(('order.urls', 'order'), namespace='order')),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),

    url(r'^', include(('goods.urls', 'goods'), namespace='goods')),
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views import View
from utils.mixin import LoginRequiredMinxin
from django.http import JsonResponse
from goods.models import DailyGoodsSKU
from utils.mixin import LoginRequiredMinxin
from django_redis import get_redis_connection
# Create your views here.


# cart/cart
class CartView(LoginRequiredMinxin, View):
    def get(self, request):
        user = request.user
        if user.is_authenticated:
            conn = get_redis_connection('default')
            cart_key = 'cart_%s' % user.id
            goods = conn.hgetall(cart_key)

            skus = []
            counts = 0
            for sku_id, count in goods.items():
                sku = DailyGoodsSKU.objects.get(id=sku_id)
                sku.count = int(count)
                skus.append(sku)
                counts += 1
                price = float(sku.price)
                total_price = int(count) * price
                sku.total_price = total_price

            content = {
                'skus': skus,
                'counts': counts
            }

            return render(request, 'cart.html', content)


# cart/add
class CartAddView(View):
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'ret': 0, 'ermsg': '登录后才能添加哦~'})

        # 获取ajax请求的参数
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        print(sku_id, count)

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'ret': 1, 'ermsg': '信息不完整'})

        # 数量校验
        try:
            count = int(count)
        except:
            return JsonResponse({'ret': 2, 'ermsg': '数量输入错误'})

        # 商品校验
        try:
            sku = DailyGoodsSKU.objects.get(id=sku_id)
        except:
            return JsonResponse({'ret': 3, 'ermsg': '商品不存在'})

        # 添加到购物车
        conn = get_redis_connection('default')
        cart_key = 'cart_%s' % user.id

        # 查找购物车数量并更新, hget查不到返回None
        cart_count = conn.hget(cart_key, sku_id)

        if cart_count:
            count += int(cart_count)

        if count > sku.stock:
            return JsonResponse({'ret': 4, 'ermsg': '商品库存不足'})

        # hset 有就更新或没有储存
        conn.hset(cart_key, sku_id, count)
        return JsonResponse({'ret': 5, 'msg': '添加成功'})


# cart/update
class CartUpdateView(View):
    def post(self, request):
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 0, 'ermsg': '数据不完整'})

        # 商品存在校验
        try:
            sku = DailyGoodsSKU.objects.get(id=sku_id)
        except:
            return JsonResponse({'res': 1, 'ermsg': '该商品不存在，请重新刷新'})

        # 商品数量校验
        try:
            count = int(count)
        except:
            return JsonResponse({'res': 2, 'ermsg': '数量错误'})

        if count > sku.stock:
            return JsonResponse({'res': 3, 'ermsg': '商品库存不足，余量' + str(sku.stock) })

        user = request.user
        conn = get_redis_connection('default')
        cart_key = 'cart_%s' % user.id

        # 更新购物车的数量
        c = conn.hset(cart_key, sku_id, count)

        return JsonResponse({'res': 4, 'msg': '更新成功'})


# cart/detele
class CartDeleteView(View):
    def post(self, request):
        sku_id = request.POST.get('sku_id')

        # 判断用户是否登录
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'ermsg': '请先登录用户'})

        # 数据校验
        if not all([sku_id]):
            return JsonResponse({'res': 1, 'ermsg': '信息错误，请重新操作'})

        # 商品校验
        try:
            sku = DailyGoodsSKU.objects.get(id=sku_id)
        except:
            return JsonResponse({'res': 2, 'ermsg': '商品不存在'})

        # 链接数据库删除数据
        conn = get_redis_connection('default')
        cart_key = 'cart_%s' % user.id

        conn.hdel(cart_key, sku_id)

        return JsonResponse({'res': 3, 'msg': '删除成功'})

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
{% load static %}
<head>
	<meta charset="utf-8">
	<!-- 移动端必有的 -->
	<meta name="viewport" content="width=device-width,user-scalable=no,
	initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
	{% block link %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/index.css'%} ">
		<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js'%}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	{% endblock link%}
	{% block title %}
		<title>首页</title>
	{% endblock title %}
</head>
<body>
		{% block content-body %}
		  {% block header-info %}
	          <div class="header">
	          		<div class="wel">快易点欢迎您!!</div>
	          		<div class="header-info">
						{% if user.is_authenticated %}
							<div class="header-user">
								欢迎您，<em class="fix-em">{{ user.username }}</em>
								<a href="/user/logout" class="quit">退出</a>
							</div>
	          			{% else %}
							<div class="header-user">
								<a href="/user/login" class="go-login">欢迎您，请登录</a>
								<a href="/user/register" class="go-register">免费注册</a>
							</div>
						{% endif %}
	          			<div class="user-info">
	          				<a href="/user/user-center-info"><span>个人中心</span></a>
	          				<a href="/user/user-center-order/1"><span>我的订单</span></a>
	          				<a href="/"><span>首页</span></a> 
	          			</div>
	          		</div>
	          </div>
          {% endblock header-info %}

          {% block logo-search%}
	          <div class="content-header">
	          		<div class="logo"><a href="/">LOGO</a></div>
				  	<form method="get" action="/search">
						<div class="search-text">
							<input type="text" name="q" placeholder="搜索关键字" class="se-text">
							<div><input type="submit" name="" class="se-btn">搜索</div>
						</div>
				    </form>
	          		<div class="cart-logo">
	          			<div class="cart-name"><a href="/cart/cart">我的购物车</a></div>
	          			<div class="cart-img"></div>
						{% if not cart_count%}
	          				<div class="cart-num"><em>0</em></div>
						{% else %}
							<div class="cart-num"><em>{{ cart_count }}</em></div>
						{% endif %}
	          		</div>
	          </div>
          {% endblock logo-search %}

          
          	{% block sum %}
	           <div class="content-headerline">
                  <div class="row">
                     <div class="dropdown">  
                         <div class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                              全部商品分类
                              <span class="caret"></span>       <!-- 这是向下的小箭头 -->
                         </div>

                         <ul class="dropdown-menu">
                              {% for type in types_header %}
                                   <li><a href="/goods/list/{{ type.id }}/1?sort=default">{{ type }}</a><span><a href="/goods/list/{{ type.id }}?sort=default">></span></a></li>
                              {% endfor %}
                         </ul>
                     </div>
                 </div>

    		  </div>

	          {% endblock sum %}
			{% block body-content %}
	          <div class="slider">
	          		
	          </div>

	          <div class="content-body">
				   {% for type_daily in types_daily %}
	          		<div class="block{{ forloop.counter }}">
	          			<div class="line{{ forloop.counter }}">
	          					<div class="select">{{ type_daily }}</div>
	          					<a href="/goods/list/{{ type_daily.id }}/1?sort=default" class="gd-more">更多></a>
	          			</div>
						{% for good in type_daily.daily_goods %}
							<ul class="gd-list">
								<li>
									<a href="/goods/daily-detail/{{ good.daily_sku.id}}/1">
										<div class="gd-name">{{ good.daily_sku.name}}</div>
										<div class="gd-img"></div>
										<div class="gd-price">{{ good.daily_sku.price }}&nbsp;{{ good.daily_sku.unit }}</div>
									</a>
								</li>
							</ul>
						{% endfor %}
	          		</div>
				   {% endfor %}

				    {% for type in types_order %}
	          		<div class="block6">
	          			<div class="line6">
	          					<div class="select">{{ type }}</div>
	          					<a href="/goods/list/{{ type.id }}/1/1?sort=default" class="gd-more">更多></a>
	          			</div>
	          			<ul class="gd-list">
							{% for good in type.order_goods %}
								<li>
									<a href="/goods/order-detail/{{ good.order_sku.id }}/1">
										<div class="gd-name">{{ good.order_sku.name}}</div>
										<div class="gd-img"></div>
										<div class="gd-price">{{ good.order_sku.price }}{{ good.order_sku.unit }}</div>
									</a>
								</li>
							{% endfor %}
	          			</ul>
	          		</div>
				   {% endfor %}

	          </div>
          {% endblock body-content %}

          {% block copyright %}
	          <hr class="h">
			  <div class="copyright">
			  		<span>xxxx</span>
			  		<span>|</span>
			  		<span>xxxx</span>
			  		<span>|</span>
			  		<span>xxxx</span>
			  		<span>|</span>
			  		<span>xxxx</span>
			  		<br>
			  		<span>xxxx asdhi 1564654 45645 56 5645 56 </span>
			  </div>
		  {% endblock copyright %}

		{% endblock content-body %}

		{% block bottomfile %}{% endblock bottomfile %}

</body>
</html>

templates/comment.html
{% extends 'center.html' %}
{% load static %}

	{% block link %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/comment.css'%} ">
		<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js'%}"></script>
	{% endblock link %}

	{% block title %}
		<title>评论商品</title>
	{% endblock title %}

		{% block content-body %}
			<div class="center-info">
				<div class="info-list">
					<ul>
						<li class="li-cl"><a href="/user/user-center-info" class="clearfix">个人中心</a> </li>
						<li class="li-cl"><a href="/user/user-info-site" class="clearfix">收货地址</a></li>
						<li class="li-cl"><a href="javascript:;" class="cur clearfix">订单评价</a> </li>
					</ul>
				</div>

				<div class="info-content">
					<form method="post">
						{% csrf_token %}
						<input type="hidden" name="order_id" value="{{ order_id }}">
						{% for sku in skus %}
						    <input type="hidden" name="total_count" value="{{ sku.order.total_count }}">
						    <input type="hidden" name="tar", value="9527">
							<li class="comment-content li-cl">
								<div class="comment-good">
									<div class="gd-img fl"></div>
									{% if sku.sku.name %}
										<div class="gd-name fl">{{ sku.sku.name }}</div>
										<div class="gd-price fl">{{ sku.price }}元</div>
										<div class="gd-count fl">{{ sku.count }}</div>
										<div class="gd-amount fl">{{ sku.amount}}元</div>
									{% else %}
										<div class="gd-name fl">{{ sku.prev.name }}</div>
										<div class="gd-price fl">{{ sku.price }}元</div>
										<div class="gd-count fl">{{ sku.count }}</div>
										<div class="gd-amount fl">{{ sku.amount}}元</div>
									{% endif %}
								</div>
								<div class="comment-text">
									{% if sku.sku.id %}
										<input type="hidden" name="sku_{{ forloop.counter }}" value="{{ sku.sku.id }}">
									{% else %}
										<input type="hidden" name="sku_{{ forloop.counter }}" value="{{ sku.prev.id }}">
									{% endif %}
									<div class="fl tp">评论内容：</div>
									<div class="fl">
										<textarea class="input-text" name='comment_{{ forloop.counter }}'></textarea>
									</div>
								</div>
							</li>
						{% endfor %}
						<div><input type="submit" name="" class="btn"></div>
					</form>
				</div>


			</div>
			<div  class="msg">{{ content }}</div>
		{% endblock content-body %}   
		{% block bottomfile %}	
		{% endblock bottomfile %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

	{% block title %}
		<title>首页</title>
	{% endblock title %}
	

		{% block body-content %}

          <div class="content-headerline">
          	   <div class="sort">
          	   			全部分类
      			</div>		
				<span><a href="#">生活必备</a></span>
				<span>|</span> 
				<span><a href="#">救急药品</a></span>
				<span>|</span> 
				<span><a href="#">诱人美食</a></span>
				<span>|</span> 
				<span><a href="#">精品书籍</a></span>
				<a href="#" class="more">更多></a>
          	   
          </div>

          <div class="slider">
          		
          </div>

          <div class="content-body">
          		<div class="block1">
          			<div class="line1">
          					<div class="select">生活必备</div>
          					<a href="#" class="gd-more">更多></a>
          			</div>
          			<ul class="gd-list">
          				<li>
          					<div class="gd-name">电池</div>
          					<div class="gd-img"></div>
          					<div class="gd-price">2元/个</div>
          				</li>
          				<li></li>
          				<li></li>
          				<li></li>
          			</ul>
          		</div>
          		<div class="block2">
          			<div class="line2">
          					<div class="select">急救药品</div>
          					<a href="#" class="gd-more">更多></a>
          			</div>
          			<ul class="gd-list">
          				<li>
          					<div class="gd-name">电池</div>
          					<div class="gd-img"></div>
          					<div class="gd-price">2元/个</div>
          				</li>
          				<li></li>
          				<li></li>
          				<li></li>
          			</ul>
          		</div>
          		<div class="block3">
          			<div class="line3">
          					<div class="select">诱人美食</div>
          					<a href="#" class="gd-more">更多></a>
          			</div>
          			<ul class="gd-list">
          				<li>
          					<div class="gd-name">电池</div>
          					<div class="gd-img"></div>
          					<div class="gd-price">2元/个</div>
          				</li>
          				<li></li>
          				<li></li>
          				<li></li>
          			</ul>
          		</div>
          		<div class="block4">
          			<div class="line4">
          					<div class="select">精品书籍</div>
          					<a href="#" class="gd-more">更多></a>
          			</div>
          			<ul class="gd-list">
          				<li>
          					<div class="gd-name">电池</div>
          					<div class="gd-img"></div>
          					<div class="gd-price">2元/个</div>
          				</li>
          				<li></li>
          				<li></li>
          				<li></li>
          			</ul>
          		</div>

          		<div class="block5">
          			<div class="line5">
          					<div class="select">居家衣橱</div>
          					<a href="#" class="gd-more">更多></a>
          			</div>
          			<ul class="gd-list">
          				<li>
          					<div class="gd-name">电池</div>
          					<div class="gd-img"></div>
          					<div class="gd-price">2元/个</div>
          				</li>
          				<li></li>
          				<li></li>
          				<li></li>
          			</ul>
          		</div>

          		<div class="block6">
          			<div class="line6">
          					<div class="select">温馨旅馆</div>
          					<a href="#" class="gd-more">更多></a>
          			</div>
          			<ul class="gd-list">
          				<li>
          					<div class="gd-name">电池</div>
          					<div class="gd-img"></div>
          					<div class="gd-price">2元/个</div>
          				</li>
          				<li></li>
          				<li></li>
          				<li></li>
          			</ul>
          		</div>
          </div>
          {% endblock body-content %}

templates/list.html
{% extends 'base.html' %}
{% load static %}

	{% block link %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/list.css'%} ">
		<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js'%}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	{% endblock link %}

	{% block title %}
	<title>商品列表</title>
	{% endblock title %}

     {% block sum %}
          <div class="content-headerline">
                  <div class="row">
                     <div class="dropdown">  
                         <div class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                              全部商品分类
                              <span class="caret"></span>       <!-- 这是向下的小箭头 -->
                         </div>

                         <ul class="dropdown-menu">
                              {% for type in type_all %}
                                   <li><a href="/goods/list/{{ type.id }}/1?sort=default">{{ type }}</a><span><a href="/goods/list/{{ type.id }}?sort=default">></span></a></li>
                              {% endfor %}
                         </ul>
                     </div>
                 </div>

          </div>

     {% endblock sum %}

	{% block body-content %}
     <div class="content-body">
        <div class="new">
     	 	<div class="new-header">新推荐</div>
     	 	<ul class="new-list">
                    {% for new in news %}
          	 		<li class="ls">
          	 			<div class="new-name"><a href="/goods/{{ new.gd_type }}/{{ new.id }}">{{ new.name }}</a> </div>
          	 			<div class="new-img"><a href=""></a></div>
          	 		</li>
     	 		{% endfor %}
     	 	</ul>
     	 </div>
     	 <div class="content-list">
     	 	<div class="list-header">
     	 		<div {% if sort == 'default' %} class="cur" {% endif %}><a href="{% url 'goods:daily-list' type.id 1 %}?sort=default"  class="fld">默认</a></div>
     	 		<div {% if sort == 'hot' %} class="cur" {% endif %}><a href="{% url 'goods:daily-list' type.id 1 %}?sort=hot"  class="fld">人气</a></div>
     	 		<div {% if sort == 'price' %} class="cur" {% endif %}><a href="{% url 'goods:daily-list' type.id 1 %}?sort=price"  class="fld">价格</a></div>
     	 	</div>
     	 	<ul class="list-content new-list">
                    {% for sku in page_skus %}
                         {% csrf_token %}
          	 		<li class="list-li ls">
          	 			<div class="list-name"><a href="/goods/daily-detail/{{ sku.id }}">{{ sku.name }}</a> </div>
          	 			<div class="list-img"></div>
          	 			<div class="list-unit">{{ sku.price }} {{ sku.unit}}</div>
          	 			<div class="add" sku_id={{sku.id }}></div>
          	 		</li>
     	 		{% endfor %}
     	 	</ul>
     	 	<ul class="list-page">
                    {% if page_skus.has_previous %}
     	 		      <li class="ls fl"><a href="{% url 'goods:daily-list' type.id page_skus.previous_page_number %}?sort={{ sort }}"><上一页</a> </li>
                    {% endif %}
                    {% for pindex in pages %}
                       {% if pindex == page_skus.number %}
          	 		<li class="ls fl"><a href="{% url 'goods:daily-list' type.id pindex %}?sort={{ sort }}" class="cur-a">{{ pindex }}</a></li>
                       {% else %}
          	 		<li class="ls fl"><a href="{% url 'goods:daily-list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</li>
          	 	   {% endif %}
                    {% endfor %}
                    {% if page_skus.has_next %}
     	 		      <li class="ls fl"><a href="{% url 'goods:daily-list' type.id page_skus.next_page_number %}?sort={{ sort }}">下一页></a> </li>
                    {% endif %}
     	 	</ul>
     	 </div>
     		
     </div>

     {% endblock body-content %}

     {% block bottomfile %}
          <script type="text/javascript">
               $(function(){

                    $('.add').click(function(){

                         var sku_id = $(this).attr('sku_id');
                         var count = 1;
                         var csrf = $('input[name="csrfmiddlewaretoken"]').val();

                         parems = {'sku_id': sku_id, 'count': count, 'csrfmiddlewaretoken': csrf}

                         $.post('/cart/add', parems, function(data){

                              if(data.ret == 5){
                                   alert(data.msg)
                              }
                              else{
                                   alert(data.ermsg)
                              }
                         })
                    })


               })
          </script>
     {% endblock bottomfile %}


         

templates/user-center-order.html
{% extends 'center.html' %}
{% load static%}
	
	{% block link %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/user-center-order.css'%} ">
		<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js'%}"></script>
	{% endblock link %}

	{% block title %}
		<title>个人中心</title>
	{% endblock title %}

		{% block content-body %}
			<div class="center-info">
				<div class="info-list">
					<ul>
						<li class="li-cl"><a href="/user/user-center-info" class="clearfix">个人中心</a> </li>
						<li class="li-cl"><a href="/user/user-info-site" class="clearfix">收货地址</a></li>
						<li class="li-cl"><a href="javascript:;" class="cur clearfix">我的订单</a> </li>
					</ul>
				</div>

				<div class="info-content">
					{% for order in page_skus %}
						{% csrf_token %}
						<li class="order-list li-cl">
							<div class="order-header">
								<div class="number fl">{{ order }}</div>
								<div class="order-time fl">{{ order.create_time }}</div>
								<div class="order-st-h fl red">{{ order.order_status_name }}</div>
							</div>
							<div class="order-info fl">
								<ul class="order-gd fl">
										{% for order_sku in order.order_skus %}
											{% if order_sku.sku %}
											    <li class="order-ls li-cl">
													<div class="gd-img fl"></div>
													<div class="gd-name fl">{{ order_sku.sku.name }}</div>
													<div class="gd-unit fl">{{ order_sku.sku.price }}    {{ order_sku.sku.unit }}</div>
													<div class="gd-num fl">{{ order_sku.count }}</div>
													<div class="gd-amount fl">{{ order_sku.amount }}元</div>
												</li>
											{% else %}
												<li class="order-ls li-cl">
													<div class="gd-img fl"></div>
													<div class="gd-name fl">{{ order_sku.prev.name }}</div>
													<div class="gd-unit fl">{{ order_sku.prev.price }}    {{ order_sku.prev.unit }}</div>
													<div class="gd-num fl">{{ order_sku.count }}</div>
													<div class="gd-amount fl">{{ order_sku.amount }}元</div>
												</li>
											{% endif %}
										{% endfor %}
								</ul>				
							
								<div class="finish_st fl red">{{ order.order_status_name }}</div>
								<div class="order-act fl"><button class="but" order_id='{{ order }}' order_status_num='{{ order.status_num }}'  sku_id={{ order.order_id }}>{{ order.status_action }}</button></div>
							</div>
						</li>
					{% endfor %}

					<ul class="page-list">
						{% if page_skus.has_previous %}
							<li class="li-cl fl li-rh"><a href="{% url 'user:user-center-order' page_skus.previous_page_number %}" class="a-cl"><上一页</a> </li>
						{% endif %}
						{% for pindex in pages %}
							{% if pindex == page_skus.number %}
								<li class="li-cl fl li-rh"><a href="{% url 'user:user-center-order' pindex %}" class="a-cl gl">{{ pindex }}</a></li>
							{% else %}
								<li class="li-cl fl li-rh"><a href="{% url 'user:user-center-order' pindex %}" class="a-cl">{{ pindex }}</a></li>
							{% endif%}
						{% endfor %}
						{% if page_skus.has_next %}
							<li class="li-cl fl li-rh"><a href="{% url 'user:user-center-order' page_skus.next_page_number %}" class="a-li a-cl">下一页></a> </li>
						{% endif %}
					</ul>
				</div>
			</div>
			<div style="display: none;" class="msg">{{ content }}</div>
		{% endblock content-body %}   
		{% block bottomfile %}
				<script type="text/javascript">
					$(function(){

							$('.order-gd').each(function(){
								var li = $(this).find('.order-ls').length;
								// alert(li)

								height_li = 70 * parseInt(li);

								$(this).css({'height': height_li + 'px'})

								$(this).siblings('.finish_st').css({'height': height_li + 'px', 'line-height': height_li + 'px'})
								$(this).siblings('.order-act').css({'height': height_li + 'px', 'line-height': height_li + 'px'})

								height_list = height_li + parseInt(74);
								$(this).parent('div').parent('.order-list').css({'height': height_list + 'px'})
							})


							$('.but').click(function(){

								var status_num = $(this).attr('order_status_num')

								var sku_id = $(this).attr('sku_id');

								if(status_num == 1){
									var order_id = $(this).attr('order_id');

									var csrf = $('input[name="csrfmiddlewaretoken"]').val();

									parems = {'order_id': order_id, 'csrfmiddlewaretoken':csrf}

									$.post('/order/pay', parems, function(data){


											if(data.res == 2){
												// window.open(data.pay_url)
												window.location.href = data.pay_url
											}

											else{
												alert(data.ermsg);
											}
									})
								}

								else if(status_num == 4){
									alert(sku_id)


									window.open('/order/comment/' + sku_id)
								}

								else{
									// alert('未处理')
								}
								
							})

							
							var msg = $('.msg').html();
							if(msg == '支付成功'){
								// alert(msg);
								window.location.href = '/user/user-center-order/1'
								var status = $('.but').attr('order_status_num');
								if(status=='4'){
									$('.order-act').text('去评价')
								}

							}
							else{
								if(msg){
									alert(msg);
								window.location.href = '/user/user-center-order/1'
								}
								
							}
										
									
					})
				</script>
		{% endblock bottomfile %}